# Site
name: 'VC Blog'
description: 'This the Blog of Vincent Cheng, and my motto is Practice makes perfect.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
disqus: 'smallmummy'
email: 'smallmummy.vc@gmail.com'
# link for subscribe in post page
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    vincent_c:
      name:           Vincent Cheng
      site:           https://smallmummy.github.io
      avatar:         assets/images/avatar1.jpg
      bio:            "Hey, This is <strong>Vincent Cheng(VC)</strong>.</p>    <p>A typical IT man in NZ with many hobbies, such as music, coffee, cooking, running, cycling, fitness, camp and etc</p>    <p>This is the blog for me typically to record things related with teachnical knowledge and experience.</p>"
      email:          smallmummy.vc@gmail.com
      twitter:        https://twitter.com/wowthemesnet
      linkedin:       https://www.linkedin.com/in/vincent-cheng-0926b541/
      github:					https://github.com/smallmummy
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: vincent-c
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]